// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjrz2fk3TM36aS1Xxk8LRfnPn35KuDZyk',
    appId: '1:1015486602166:web:05e28f6210c3b7d7433f17',
    messagingSenderId: '1015486602166',
    projectId: 'eats-527e9',
    authDomain: 'eats-527e9.firebaseapp.com',
    databaseURL: 'https://eats-527e9-default-rtdb.firebaseio.com',
    storageBucket: 'eats-527e9.firebasestorage.app',
    measurementId: 'G-P82MGSQSDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RBASJf0WTl1h4y1mQLnPofRpgJjcIHY',
    appId: '1:1015486602166:android:a286e3bdf4d508f8433f17',
    messagingSenderId: '1015486602166',
    projectId: 'eats-527e9',
    databaseURL: 'https://eats-527e9-default-rtdb.firebaseio.com',
    storageBucket: 'eats-527e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGSJLmFgT9zBerxLIQEqHnHgS5HuNSrOA',
    appId: '1:1015486602166:ios:41a82b38f25a1047433f17',
    messagingSenderId: '1015486602166',
    projectId: 'eats-527e9',
    databaseURL: 'https://eats-527e9-default-rtdb.firebaseio.com',
    storageBucket: 'eats-527e9.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );
}
